allowBuilds:
  '@prisma/engines': set this to true or false
  argon2: set this to true or false
  bcrypt: true
  prisma: set this to true or false
  sharp: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
